# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(max_length=255)),
                ('q1', models.CharField(max_length=255)),
                ('q2', models.CharField(max_length=255)),
                ('q3', models.CharField(max_length=255)),
                ('q4', models.CharField(max_length=255)),
                ('q5', models.CharField(max_length=255)),
                ('q6', models.CharField(max_length=255)),
                ('q7', models.CharField(max_length=255)),
                ('q8', models.CharField(max_length=255)),
                ('q9', models.CharField(max_length=255)),
                ('q10', models.CharField(max_length=255)),
                ('q11', models.CharField(max_length=255)),
                ('q12', models.CharField(max_length=255)),
                ('q13', models.CharField(max_length=255)),
                ('q14', models.CharField(max_length=255)),
                ('q15', models.CharField(max_length=255)),
            ],
        ),
    ]
