# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
