# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20180407_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='Cusers',
        ),
    ]
